// AUTHENTICATION
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const AUTH_USER = 'AUTH_USER';

// APPLICATION
export const FETCH_TOURS_RESOLVED = 'FETCH_TOURS_RESOLVED';
export const FETCH_TOURS_PENDING = 'FETCH_TOURS_PENDING';
export const FETCH_TOURS_REJECTED = 'FETCH_TOURS_REJECTED';

export const FETCH_SHOWS_RESOLVED = 'FETCH_SHOWS_RESOLVED';
export const FETCH_SHOWS_PENDING = 'FETCH_SHOWS_PENDING';
export const FETCH_SHOWS_REJECTED = 'FETCH_SHOWS_REJECTED';

export const FETCH_ORDERS_RESOLVED = 'FETCH_ORDERS_RESOLVED';
export const FETCH_ORDERS_PENDING = 'FETCH_ORDERS_PENDING';
export const FETCH_ORDERS_REJECTED = 'FETCH_ORDERS_REJECTED';

export const SEARCH = 'SEARCH';

// EMAIL
export const FETCH_EMAIL_RESOLVED = 'FETCH_EMAIL_RESOLVED';
export const FETCH_EMAIL_PENDING = 'FETCH_EMAIL_PENDING';
export const FETCH_EMAIL_REJECTED = 'FETCH_EMAIL_REJECTED';

export const SAVE_EMAIL_RESOLVED = 'SAVE_EMAIL_RESOLVED';
export const SAVE_EMAIL_PENDING = 'SAVE_EMAIL_PENDING';
export const SAVE_EMAIL_REJECTED = 'SAVE_EMAIL_REJECTED';

export const SEND_EMAIL_RESOLVED = 'SEND_EMAIL_RESOLVED';
export const SEND_EMAIL_PENDING = 'SEND_EMAIL_PENDING';
export const SEND_EMAIL_REJECTED = 'SEND_EMAIL_REJECTED';

// USER
export const UPDATE_USER_RESOLVED = 'UPDATE_USER_RESOLVED';
export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED';

export const FETCH_USERS_RESOLVED = 'FETCH_USERS_RESOLVED';
export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';

export const DELETE_USER_RESOLVED = 'DELETE_USER_RESOLVED';
export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_REJECTED = 'DELETE_USER_REJECTED';
