// AUTHENTICATION
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const AUTH_USER = 'AUTH_USER';

// SHOPIFY
export const FETCH_TOURS_RESOLVED = 'FETCH_TOURS_RESOLVED';
export const FETCH_TOURS_PENDING = 'FETCH_TOURS_PENDING';
export const FETCH_TOURS_REJECTED = 'FETCH_TOURS_REJECTED';
